# This workflow runs in a public repo, scrapes/tests links, and pushes the results to a private repo.

name: V2Ray Scraper -> Push to Private Repo

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' 

jobs:
  scrape-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the public repository (where this workflow runs)
      - name: Check out Public Repo
        uses: actions/checkout@v4
        with:
          repository: mrbign0b/v # <-- IMPORTANT: CHANGE THIS
          path: public_repo

      # Step 2: Check out the private repository (where results will be saved)
      - name: Check out Private Repo
        uses: actions/checkout@v4
        with:
          repository: mrbign0b/v2raylinksave- # <-- IMPORTANT: CHANGE THIS
          path: private_repo
          token: ${{ secrets.REPO_ACCESS_PRI }}

      # Step 3: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 4: Install Python dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r public_repo/requirements.txt

      # Step 5: Run the stateful scraper script
      # The script is now aware of the directory structure
      - name: Run Stateful V2Ray Scraper
        run: python public_repo/main.py

      # Step 6: Commit and push all changes to the private repository
      - name: Commit and Push to Private Repo
        run: |
          cd private_repo
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action-bot@github.com"
          # Add the main output file AND the directory containing source histories
          git add working_servers.txt
          git add source_links/
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update working servers and source history"
            git push
          fi
